return {
  -- "utilyre/barbecue.nvim",
  -- name = "barbecue",
  -- version = "*",
  -- dependencies = {
  --   "SmiteshP/nvim-navic",
  --   "nvim-tree/nvim-web-devicons", -- optional dependency
  -- },
  -- opts = {
  --   -- configurations go here
  --   theme = {
  --     -- this highlight is used to override other highlights
  --     -- you can take advantage of its `bg` and set a background throughout your winbar
  --     -- (e.g. basename will look like this: { fg = "#c0caf5", bold = true })
  --     -- normal = { bg = "#1F1F28", fg = "#DCD7BA" },
  --     -- normal = {bg =" #1F1F28",  fg="#DCD7BA"},
  --     -- normal = { fg = "#C0A36E" },
  --
  --     -- # normal
  --     -- color0 #16161D
  --     -- color1 #C34043
  --     -- color2 #76946A
  --     -- color3 #C0A36E
  --     -- color4 #7E9CD8
  --     -- color5 #957FB8
  --     -- color6 #6A9589
  --     -- color7 #C8C093
  --     --
  --     -- # bright
  --     -- color8  #727169
  --     -- color9  #E82424
  --     -- color10 #98BB6C
  --     -- color11 #E6C384
  --     -- color12 #7FB4CA
  --     -- color13 #938AA9
  --     -- color14 #7AA89F
  --     -- color15 #DCD7BA
  --     --
  --     --
  --     -- # extended colors
  --     -- color16 #FFA066
  --     -- color17 #FF5D62
  --
  --     -- these highlights correspond to symbols table from config
  --     -- ellipsis = { fg = "#737aa2" },
  --     -- separator = { fg = "#737aa2" },
  --     -- modified = { fg = "#737aa2" },
  --
  --     -- these highlights represent the _text_ of three main parts of barbecue
  --     -- dirname = { fg = "#737aa2" },
  --     -- basename = { bold = true },
  --     -- context = {},
  --
  --     -- these highlights are used for context/navic icons
  --     -- context_file = { fg = "#ac8fe4" },
  --     -- context_module = { fg = "#ac8fe4" },
  --     -- context_namespace = { fg = "#ac8fe4" },
  --     -- context_package = { fg = "#ac8fe4" },
  --     -- context_class = { fg = "#ac8fe4" },
  --     -- context_method = { fg = "#ac8fe4" },
  --     -- context_property = { fg = "#ac8fe4" },
  --     -- context_field = { fg = "#ac8fe4" },
  --     -- context_constructor = { fg = "#ac8fe4" },
  --     -- context_enum = { fg = "#ac8fe4" },
  --     -- context_interface = { fg = "#ac8fe4" },
  --     -- context_function = { fg = "#ac8fe4" },
  --     -- context_variable = { fg = "#ac8fe4" },
  --     -- context_constant = { fg = "#ac8fe4" },
  --     -- context_string = { fg = "#ac8fe4" },
  --     -- context_number = { fg = "#ac8fe4" },
  --     -- context_boolean = { fg = "#ac8fe4" },
  --     -- context_array = { fg = "#ac8fe4" },
  --     -- context_object = { fg = "#ac8fe4" },
  --     -- context_key = { fg = "#ac8fe4" },
  --     -- context_null = { fg = "#ac8fe4" },
  --     -- context_enum_member = { fg = "#ac8fe4" },
  --     -- context_struct = { fg = "#ac8fe4" },
  --     -- context_event = { fg = "#ac8fe4" },
  --     -- context_operator = { fg = "#ac8fe4" },
  --     -- context_type_parameter = { fg = "#ac8fe4" },
  --   },
  -- },
}
